version: '2'

services:
    drupal:
        image: drupal:latest
        ports:
            - '8080:80'
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: drupaldb
            POSTGRES_USER: hly
            POSTGRES_PASSWORD: pass